### ISSUE TITLE
Missing include-file

### ISSUE THREAD

**Issue by RaffiCologne** [gmag11/ESPNtpClient#1]
C:\Users\raffi\Documents\Arduino\libraries\ESPNtpClient-main\src/ESPNtpClient.h:41:16: fatal error: TZ.h: No such file or directory

If i look there, the TZ.h is missing.

My mistake or your fault?

Greeetings,
Ralf

**Comment by RaffiCologne** [comment]
After updating to the actual esp8266 core,  everything is fine

**Comment by gmag11** [comment]
Good to know. Thank you
