### ISSUE TITLE
how to retrieve the hour, minute and second in 3 variables?

### ISSUE THREAD

**Issue by stef-ladefense** [gmag11/ESPNtpClient#10]
Hello
I'm going to ask a silly question
how to retrieve the hour, minute and second in 3 variables?

thx

**Comment by gmag11** [comment]
Espressif include UNIX compatible time library. You can use standard function calls to get time. Check this doc: https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_chapter/libc_21.html

The function you are looking for is `localtime ()`

**Comment by stef-ladefense** [comment]
merci !
avant j'utilisais timelib, qui était très bien,
avec ta nouvelle librairie, çà génère des pages d'erreurs !
