### ISSUE TITLE
Making the library esp idf compatible (no Arduino libraries)

### ISSUE THREAD

**Issue by trichl** [gmag11/ESPNtpClient#18]
Hey there,

that's rather a feature request than an issue. First of all, thanks for the cool library. I think it would be super awesome to make the code Arduino independent (esp idf only). Have you ever thought about porting it? 

Best, Timm

**Comment by gmag11** [comment]
That's a great idea. It should not be difficult. The challenge here is that I'm not used to program using IDF directly so I do not have the skills to do the integration. Feel free to do a fork or a pull request
