### ISSUE TITLE
Side-Efect - WiFi.reconnect

### ISSUE THREAD

**Issue by vborcea** [gmag11/ESPNtpClient#19]
Very nice work with the library.
I have one problem with it: the WiFi.reconnect. Do you think that it's OK to make this part optional?
Like, when the NTP.begin is called to receive a parameter that will say if the library should call the reconnect or not?
Please note that some projects are already handling these Wifi problems and the WifiReconnect improvement overlaps with them.
I can make a PR with this if you think that it's OK with you.

**Comment by gmag11** [comment]
Hi, this is a nice idea. I'll implement it with a optional parameter `bool manage_wifi` with `true` as default, so that it can be disabled if you like. I'll put a note here when it is in dev branch. Thanks!

**Comment by gmag11** [comment]
It is there. Please test it and give me some feedback here :)
