### ISSUE TITLE
NTP.getUptimeString() returns more than 3 days after boot

### ISSUE THREAD

**Issue by solideblock** [gmag11/ESPNtpClient#2]
Hi gmag11,

You can't imagine how long I've been waiting to see you coming back with an updated version of your library. I really want to thank you for sharing this with the community. 

I've just updated my code and something strange is happening with  NTP.getUptimeString() . The string returns a high value just after I boot the device. 

A sample of my main page which is build from the following string:

```
String Uptime = NTP.getUptimeString();
Uptime += " - FirstSync  : ";
Uptime += NTP.getTimeDateString (NTP.getFirstSync());
```
Result:

> Uptime : 3 days 00:57:56 - FirstSync : 28/11/2020 17:07:45

For info, the current system time when i copied the value was : 28/11/2020 17:20:45

**Comment by gmag11** [comment]
Yes, this was a bug introduced in earlier versions. In current one (0.1.0) it is already fixed. Thanks for letting me know
