### ISSUE TITLE
ESP8266 SDK 3.X Compile failed - Fixed

### ISSUE THREAD

**Issue by vslinuxdotnet** [gmag11/ESPNtpClient#21]
Hello,
I fixed some problems with your lib in the new ESP8266 SDK, the 3.X.

In file: ESPNtpClient.h
`
char* getTimeStr (timeval moment) {
tm* local_tm = localtime (&moment.tv_usec);
`
to
`
char* getTimeStr (timeval moment) {
tm* local_tm = localtime ((time_t*) &moment.tv_usec);
`

In file: ESPNtpClient.cpp
`char* dumpNTPPacket (byte* data, size_t length, char* buffer, int len) {`
to
`char* dumpNTPPacket (uint8_t* data, size_t length, char* buffer, int len) {`

Regards,

VS

**Comment by gmag11** [comment]
Fixed on https://github.com/gmag11/ESPNtpClient/commit/12f30aa6ef9e71d300840f4ad0d70b83391c4fee

Thank you!
