### ISSUE TITLE
NTP.getTime not public

### ISSUE THREAD

**Issue by RaffiCologne** [gmag11/ESPNtpClient#4]
Good morning, using your Lib as replacement for NTPClientLib.
Everything is running fine till now.
Using NTP.getTime() results in 
C:\Users\raffi\Documents\Arduino\libraries\ESPNtpClient-main\src/ESPNtpClient.h:153:10: error: 'void NTPClient::getTime()' is protected

     void getTime ();

Looking in ESPNtpLib.h you commented:

 /**
    * Starts a NTP time request to server. Returns a time in UNIX time format. Normally only called from library.
    * Kept in public section to allow direct NTP request.
    */
    void getTime ();

Is there another function to manually fire a request or what i am doing wrong?
Regards,
Ralf

**Comment by gmag11** [comment]
Just fixed in last release. Why do you need that? I'd like to know the use case.

**Comment by RaffiCologne** [comment]
Hi, thanks for your fast reply.

The picture shows a part of a web-interface.

If the user clicks the Button, time sync should happen manually.

 



 

 

 

Von: Germán Martín [mailto:notifications@github.com] 
Gesendet: Dienstag, 1. Dezember 2020 22:26
An: gmag11/ESPNtpClient
Cc: RaffiCologne; Author
Betreff: Re: [gmag11/ESPNtpClient] NTP.getTime not public (#4)

 

Just fixed in last release. Why do you need that? I'd like to know the use case.

**Comment by gmag11** [comment]
Thanks, then I close this issue
