### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by stef-ladefense** [gmag11/ESPNtpClient#8]
very good for this new library 👍 

please make full compatibility with your old library
->
bool NTPClient::begin (String ntpServerName, int8_t timeZone, bool daylight, int8_t minutes, AsyncUDP* udp_conn)

thx thx thx

**Comment by gmag11** [comment]
Sorry, I've tried to keep this as similar as possible but library internals is very different. For instance, it may not use UDP class anymore and time zone / daylight parameters are passed in a completely different way. Check examples, it is very easy to modify your code to get it working.
